use super::state::{HelpTab, Overlay};

#[derive(Debug, Clone)]
pub enum AppEvent {
    Noop,
    OpenOverlay(Overlay),
    CloseOverlay,
    SubmitComposer,
    InsertNewline,
    InputChar(char),
    Backspace,
    DeleteForward,
    MoveCursorLeft,
    MoveCursorRight,
    MoveCursorHome,
    MoveCursorEnd,
    MoveCursorUp,
    MoveCursorDown,
    ScrollTranscript(i32),
    MoveCommandSelection(i32),
    MoveProviderSelection(i32),
    MoveModelSelection(i32),
    MoveOpenAiProfileSelection(i32),
    MoveAuthModeSelection(i32),
    MoveReasoningEffortSelection(i32),
    MoveResumeSelection(i32),
    SetProviderSelection(usize),
    SetModelSelection(usize),
    SetOpenAiProfileSelection(usize),
    SetAuthModeSelection(usize),
    SetReasoningEffortSelection(usize),
    SetResumeSelection(usize),
    SelectPendingOption(usize),
    CycleModelSelection,
    SaveBaseUrlInput,
    SaveApiKeyInput,
    SaveModelNameInput,
    SaveOpenAiProfileLabelInput,
    SelectHelpTab(HelpTab),
    ApplyOverlaySelection,
}
